// ============================================================================
// Task F6 — Centralized Block Data Table (src/config/blocks.js)
// Stable numeric IDs + original names + tool tiers + drops + gravity & light
// ============================================================================

export const TILE_INDEX = {
  grass_top_a: 0,
  grass_top_b: 1,
  grass_top_c: 2,
  grass_side: 3,
  dirt_a: 4,
  dirt_b: 5,
  stone_a: 6,
  stone_b: 7,
  stone_c: 8,
  cobblestone: 9,
  mossy_cobble: 10,
  bedrock: 11,
  sand_a: 12,
  sand_b: 13,
  sandstone_top: 14,
  sandstone_side: 15,
  gravel: 16,
  oak_log_top: 17,
  oak_log_side: 18,
  oak_planks: 19,
  birch_log_top: 20,
  birch_log_side: 21,
  birch_planks: 22,
  pine_log_top: 23,
  pine_log_side: 24,
  pine_planks: 25,
  oak_leaves_a: 26,
  oak_leaves_b: 27,
  birch_leaves: 28,
  pine_leaves: 29,
  glass: 30,
  bricks: 31,
  stone_bricks: 32,
  coal_ore: 33,
  iron_ore: 34,
  gold_ore: 35,
  redstone_ore: 36,
  emerald_ore: 37,
  diamond_ore: 38,
  snow: 39,
  snow_side: 40,
  ice: 41,
  glowstone: 42,
  obsidian: 43,
  water: 44,
  lava: 45,
  crafting_top: 46,
  crafting_side: 47,
  furnace_front: 48,
  furnace_side: 49,
  furnace_top: 50,
  bookshelf: 51,
  tnt_top: 52,
  tnt_side: 53,
  tnt_bottom: 54,
  pumpkin_top: 55,
  pumpkin_side: 56,
  pumpkin_face: 57,
  melon_top: 58,
  melon_side: 59,
  cactus_top: 60,
  cactus_side: 61,
  cactus_bottom: 62,
  deep_stone: 63,
  coarse_dirt: 64,
  clay: 65,
  red_sand: 66,
  copper_ore: 67,
  ruby_ore: 68,
  azure_ore: 69,
  lumen_lamp: 70,
};

export const BLOCK_DATA_TABLE = [
  {
    id: 'grass',
    numericId: 1,
    name: 'Grass Block',
    textures: { top: 0, side: 3, bottom: 4, topVariants: [0, 1, 2] },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 0,
    hardness: 0.6,
    tool: 'shovel',
    minToolTier: 0,
    drops: [{ item: 'dirt', count: 1, chance: 1.0 }],
    stackSize: 64,
    flammable: false,
    gravity: false,
  },
  {
    id: 'dirt',
    numericId: 2,
    name: 'Dirt',
    textures: { top: 4, side: 4, bottom: 4, topVariants: [4, 5] },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 0,
    hardness: 0.5,
    tool: 'shovel',
    minToolTier: 0,
    drops: [{ item: 'dirt', count: 1, chance: 1.0 }],
    stackSize: 64,
    flammable: false,
    gravity: false,
  },
  {
    id: 'stone',
    numericId: 3,
    name: 'Stone',
    textures: { top: 6, side: 6, bottom: 6, topVariants: [6, 7, 8] },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 0,
    hardness: 1.5,
    tool: 'pick',
    minToolTier: 1,
    drops: [{ item: 'cobblestone', count: 1, chance: 1.0 }],
    stackSize: 64,
    flammable: false,
    gravity: false,
  },
  {
    id: 'wood',
    numericId: 4,
    name: 'Oak Log',
    textures: { top: 17, side: 18, bottom: 17 },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 0,
    hardness: 1.2,
    tool: 'axe',
    minToolTier: 0,
    drops: [{ item: 'wood', count: 1, chance: 1.0 }],
    stackSize: 64,
    flammable: true,
    gravity: false,
  },
  {
    id: 'leaves',
    numericId: 5,
    name: 'Oak Leaves',
    textures: { top: 26, side: 26, bottom: 26, topVariants: [26, 27] },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 0,
    hardness: 0.2,
    tool: 'shears',
    minToolTier: 0,
    drops: [{ item: 'wood', count: 1, chance: 0.25 }],
    stackSize: 64,
    flammable: true,
    gravity: false,
  },
  {
    id: 'glass',
    numericId: 6,
    name: 'Clear Glass',
    textures: { top: 30, side: 30, bottom: 30 },
    shape: 'cube',
    solid: true,
    transparent: true,
    opaque: false,
    lightEmit: 0,
    hardness: 0.3,
    tool: 'hand',
    minToolTier: 0,
    drops: [],
    stackSize: 64,
    flammable: false,
    gravity: false,
  },
  {
    id: 'brick',
    numericId: 7,
    name: 'Bricks',
    textures: { top: 31, side: 31, bottom: 31 },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 0,
    hardness: 2.0,
    tool: 'pick',
    minToolTier: 1,
    drops: [{ item: 'brick', count: 1, chance: 1.0 }],
    stackSize: 64,
    flammable: false,
    gravity: false,
  },
  {
    id: 'sand',
    numericId: 8,
    name: 'Sand',
    textures: { top: 12, side: 12, bottom: 12, topVariants: [12, 13] },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 0,
    hardness: 0.5,
    tool: 'shovel',
    minToolTier: 0,
    drops: [{ item: 'sand', count: 1, chance: 1.0 }],
    stackSize: 64,
    flammable: false,
    gravity: true, // Task F6: Sand falls when unsupported!
  },
  {
    id: 'torch',
    numericId: 9,
    name: 'Lumen Block',
    textures: { top: 42, side: 42, bottom: 42 },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 15,
    hardness: 0.3,
    tool: 'hand',
    minToolTier: 0,
    drops: [{ item: 'torch', count: 1, chance: 1.0 }],
    stackSize: 64,
    flammable: false,
    gravity: false,
  },
  {
    id: 'gravel',
    numericId: 10,
    name: 'Gravel',
    textures: { top: 16, side: 16, bottom: 16 },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 0,
    hardness: 0.6,
    tool: 'shovel',
    minToolTier: 0,
    drops: [{ item: 'gravel', count: 1, chance: 1.0 }],
    stackSize: 64,
    flammable: false,
    gravity: true, // Task F6: Gravel falls when unsupported!
  },
  {
    id: 'coal_ore',
    numericId: 11,
    name: 'Coal Ore',
    textures: { top: 33, side: 33, bottom: 33 },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 0,
    hardness: 2.2,
    tool: 'pick',
    minToolTier: 1,
    drops: [{ item: 'coal_ore', count: 2, chance: 1.0 }],
    stackSize: 64,
    flammable: false,
    gravity: false,
  },
  {
    id: 'iron_ore',
    numericId: 12,
    name: 'Iron Ore',
    textures: { top: 34, side: 34, bottom: 34 },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 0,
    hardness: 2.8,
    tool: 'pick',
    minToolTier: 2,
    drops: [{ item: 'iron_ore', count: 1, chance: 1.0 }],
    stackSize: 64,
    flammable: false,
    gravity: false,
  },
  {
    id: 'gold_ore',
    numericId: 13,
    name: 'Gold Ore',
    textures: { top: 35, side: 35, bottom: 35 },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 0,
    hardness: 3.0,
    tool: 'pick',
    minToolTier: 3,
    drops: [{ item: 'gold_ore', count: 1, chance: 1.0 }],
    stackSize: 64,
    flammable: false,
    gravity: false,
  },
  {
    id: 'redstone_ore',
    numericId: 14,
    name: 'Spark Ore',
    textures: { top: 36, side: 36, bottom: 36 },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 9,
    hardness: 2.8,
    tool: 'pick',
    minToolTier: 2,
    drops: [{ item: 'redstone_ore', count: 3, chance: 1.0 }],
    stackSize: 64,
    flammable: false,
    gravity: false,
  },
  {
    id: 'emerald_ore',
    numericId: 15,
    name: 'Ruby / Emerald Ore',
    textures: { top: 37, side: 37, bottom: 37 },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 5,
    hardness: 3.2,
    tool: 'pick',
    minToolTier: 3,
    drops: [{ item: 'emerald_ore', count: 1, chance: 1.0 }],
    stackSize: 64,
    flammable: false,
    gravity: false,
  },
  {
    id: 'gem_ore',
    numericId: 16,
    name: 'Gem Ore (Cyan Crystal)',
    textures: { top: 38, side: 38, bottom: 38 },
    shape: 'cube',
    solid: true,
    transparent: false,
    opaque: true,
    lightEmit: 8,
    hardness: 3.5,
    tool: 'pick',
    minToolTier: 3,
    drops: [{ item: 'gem_ore', count: 2, chance: 1.0 }],
    stackSize: 64,
    flammable: false,
    gravity: false,
  },
];

export const STABLE_NAME_TO_ID = Object.fromEntries(
  BLOCK_DATA_TABLE.map((b) => [b.id, b.numericId])
);
