// ============================================================================
// Centralized Seeded Ore Vein Configuration (Task F4)
// ============================================================================

export const SAVE_WORLD_VERSION = 3; // Bumped for Task F4 terrain/cave/ore upgrade

export const ORE_CONFIGS = [
  {
    id: 'coal_ore',
    name: 'Coal Ore',
    minY: 5,
    maxY: 60,
    peakY: 34,
    veinsPerChunk: 9,
    veinSizeMin: 5,
    veinSizeMax: 9,
    rarity: 0.92,
    distribution: 'triangular',
    biomeBonus: { mountains: 1.25, swamp: 1.15 },
    caveExposureBonus: 0.035,
  },
  {
    id: 'iron_ore',
    name: 'Iron Ore',
    minY: 5,
    maxY: 45,
    peakY: 24,
    veinsPerChunk: 6,
    veinSizeMin: 4,
    veinSizeMax: 7,
    rarity: 0.82,
    distribution: 'triangular',
    biomeBonus: { mountains: 1.45, taiga: 1.2 },
    caveExposureBonus: 0.028,
  },
  {
    id: 'redstone_ore',
    name: 'Copper / Redstone Ore',
    minY: 12,
    maxY: 52,
    peakY: 30,
    veinsPerChunk: 5,
    veinSizeMin: 4,
    veinSizeMax: 6,
    rarity: 0.75,
    distribution: 'triangular',
    biomeBonus: { desert: 1.3, savanna: 1.2 },
    caveExposureBonus: 0.022,
  },
  {
    id: 'gold_ore',
    name: 'Gold Ore',
    minY: 5,
    maxY: 25,
    peakY: 14,
    veinsPerChunk: 2,
    veinSizeMin: 3,
    veinSizeMax: 5,
    rarity: 0.52,
    distribution: 'triangular',
    biomeBonus: { desert: 1.4, mountains: 1.25 },
    caveExposureBonus: 0.015,
  },
  {
    id: 'emerald_ore',
    name: 'Emerald Ore',
    minY: 5,
    maxY: 28,
    peakY: 15,
    veinsPerChunk: 1,
    veinSizeMin: 2,
    veinSizeMax: 4,
    rarity: 0.42,
    distribution: 'triangular',
    biomeBonus: { mountains: 2.2 },
    caveExposureBonus: 0.012,
  },
  {
    id: 'gem_ore',
    name: 'Crystal / Diamond Ore',
    minY: 5,
    maxY: 16,
    peakY: 9,
    veinsPerChunk: 1,
    veinSizeMin: 2,
    veinSizeMax: 4,
    rarity: 0.48,
    distribution: 'triangular',
    biomeBonus: { mountains: 1.2 },
    caveExposureBonus: 0.014,
  },
];
